//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by linkage.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_LINKAGTYPE                  129
#define IDS_EDIT_MENU                   129
#define IDS_RIBBON_OPENSAMPLE           130
#define IDS_STRING131                   131
#define IDS_RIBBON_INTERACTIVE          132
#define ID_SIMULATE_INTERACTIVE         133
#define ID_INSERT_ACTUATOR              134
#define IDS_RIBBON_INSERT_ACTUATOR      135
#define IDD_CONNECTOR_PROPERTIES        139
#define IDB_BITMAP1                     142
#define IDI_ICON1                       143
#define IDI_ICON2                       144
#define IDI_ICON3                       145
#define IDI_ICON4                       146
#define IDI_ICON5                       147
#define IDI_ICON6                       148
#define IDD_SELECT_IMAGE_OPTION         149
#define IDB_BITMAP2                     150
#define IDD_LINK_PROPERTIES             150
#define IDR_POPUP_EDIT                  152
#define IDC_EDIT1                       1002
#define IDC_EDIT7                       1003
#define IDC_RADIO1                      1005
#define IDC_RADIO2                      1006
#define IDC_RADIO3                      1007
#define IDC_RPMPROMPT                   1008
#define IDC_RADIO7                      1008
#define IDC_CHECK1                      1009
#define IDC_RPMPROMPT2                  1009
#define IDC_RADIO4                      1010
#define IDC_SPIN1                       1010
#define IDC_RADIO5                      1011
#define IDC_RADIO6                      1011
#define IDC_SPIN2                       1011
#define IDC_RADIO9                      1012
#define IDC_BUTTON1                     1018
#define IDC_COMMAND4                    1019
#define IDC_BUTTON2                     1019
#define IDC_BUTTON3                     1020
#define IDC_BUTTON4                     1021
#define ID_CONTROL_WINDOW               1022
#define ID_EDIT_MAKEANCHOR              1023
#define IDC_COMMAND1                    2000
#define IDC_CHECK2                      2001
#define IDB_BITMAP4                     2002
#define IDC_EDIT2                       2002
#define IDC_CHECK3                      2003
#define IDC_EDIT4                       2003
#define IDD_DIALOG1                     2004
#define IDD_ABOUT                       2004
#define IDC_EDIT6                       2004
#define IDD_START_RECORD                2005
#define IDI_ICON8                       2006
#define IDD_POINT_PROPERTIES            2006
#define IDS_SAMPLE_ACTUATOR             2007
#define IDD_DRAWINGLINK_PROPERTIES      2007
#define IDS_SAMPLE_ACTUATOR2            2008
#define IDS_SAMPLE_ACTUATOR3            2009
#define IDS_SAMPLE_COMPLICATED          3002
#define IDS_SAMPLE_REVERSER             3003
#define IDS_SAMPLE_SCISSORS             3004
#define IDS_SAMPLE_VARYSPEED            3005
#define IDS_SAMPLE_FINGERBOX            3006
#define IDS_SAMPLE_WATT                 3007
#define IDS_RIBBON_PAUSE                3009
#define ID_SIMULATION_PAUSE             3010
#define IDS_RIBBON_FORWARD              3011
#define ID_SIMULATE_FORWARD             3012
#define IDS_RIBBON_BACKWARD             3013
#define ID_SIMULATE_BACKWARD            3014
#define ID_SIMULATE_FORWARD_BIG         3015
#define ID_SIMULATE_BACKWARD_BIG        3016
#define ID_EDIT_SET_RATIO               3017
#define IDS_RIBBON_SET_RATIO            3018
#define IDS_RIBBON_HELPCAT              3019
#define IDS_RIBBON_HELPABOUT            3020
#define ID_FILE_HELPABOUT               3021
#define IDS_RIBBON_HELPDOC              3022
#define ID_FILE_HELPDOC                 3023
#define IDS_RIBBON_HELP                 3024
#define IDB_NAVIGATION_LARGE_HC         4100
#define IDB_PAGES                       4101
#define IDB_PAGES_HC                    4102
#define IDB_PAGES_SMALL                 4103
#define IDB_PAGES_SMALL_HC              4104
#define IDR_THEME_MENU                  4105
#define ID_SET_STYLE                    4106
#define ID_VIEW_APPLOOK_WIN_2000        4107
#define ID_VIEW_APPLOOK_OFF_XP          4108
#define ID_VIEW_APPLOOK_WIN_XP          4109
#define ID_VIEW_APPLOOK_OFF_2003        4110
#define ID_VIEW_APPLOOK_VS_2005         4111
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   4112
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  4113
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 4114
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   4115
#define ID_TOOLS_OPTIONS                4116
#define ID_VIEW_CAPTION_BAR             4117
#define IDB_INFO                        4118
#define IDS_CAPTION_BUTTON              4119
#define IDS_CAPTION_BUTTON_TIP          4120
#define IDS_CAPTION_TEXT                4121
#define IDS_CAPTION_IMAGE_TIP           4122
#define IDS_CAPTION_IMAGE_TEXT          4123
#define IDS_MYCALENDARS                 4124
#define IDS_CALENDAR                    4125
#define IDS_SHORTCUTS                   4126
#define IDS_FOLDERS                     4127
#define IDS_OUTLOOKBAR                  4128
#define IDS_RIBBON_FILE                 4129
#define IDS_RIBBON_NEW                  4130
#define IDS_RIBBON_OPEN                 4131
#define IDS_RIBBON_SAVE                 4132
#define IDS_RIBBON_SAVEAS               4133
#define IDS_RIBBON_PRINT                4134
#define IDS_RIBBON_PRINT_LABEL          4135
#define IDS_RIBBON_PRINT_QUICK          4136
#define IDS_RIBBON_PRINT_PREVIEW        4137
#define IDS_RIBBON_PRINT_SETUP          4138
#define IDS_RIBBON_CLOSE                4139
#define IDS_RIBBON_RECENT_DOCS          4140
#define IDS_RIBBON_EXIT                 4141
#define IDS_RIBBON_HOME                 4142
#define IDS_RIBBON_CLIPBOARD            4143
#define IDS_RIBBON_PASTE                4144
#define IDS_RIBBON_CUT                  4145
#define IDS_RIBBON_COPY                 4146
#define IDS_RIBBON_SELECTALL            4147
#define IDS_RIBBON_WINDOW               4148
#define IDS_RIBBON_WINDOWS              4149
#define IDS_RIBBON_STYLE                4150
#define IDS_RIBBON_STYLE_TIP            4151
#define IDS_RIBBON_STYLE_DESC           4152
#define IDS_RIBBON_STATUSBAR            4153
#define IDS_RIBBON_VIEW                 4154
#define IDS_RIBBON_PROPERTIES           4155
#define IDS_RIBBON_CONNECTPROPERTIES    4156
#define IDS_RIBBON_CAPTIONBAR           4157
#define IDS_RIBBON_VIEW_DATA            4161
#define IDS_RIBBON_VIEW_DEBUG           4162
#define IDS_RIBBON_VIEW_ZOOMIN          4163
#define IDS_RIBBON_VIEW_ZOOMOUT         4164
#define IDS_RIBBON_SIMULATION           4165
#define IDS_RIBBON_RUN                  4166
#define IDS_RIBBON_SIMULATE             4167
#define IDS_RIBBON_STOP                 4168
#define ID_SIMULATION_RUN               4169
#define ID_SIMULATION_STOP              4170
#define ID_SIMULATION_SIMULATE          4171
#define IDS_RIBBON_LINKPROPERTIES       4172
#define IDS_RIBBON_SAMPLES              4173
#define IDB_SAMPLE_GALLERY              4174
#define IDS_RIBBON_INSERT               4175
#define IDB_SAMPLE_GALLERY1             4175
#define IDB_INSERT_POPUP_GALLERY        4175
#define IDS_RIBBON_ACTION               4176
#define IDS_RIBBON_CONNECT              4177
#define IDS_RIBBON_JOIN                 4178
#define IDS_RIBBON_COMBINE              4179
#define IDS_RIBBON_SLIDE                4180
#define IDS_RIBBON_SPLIT                4181
#define ID_RIBBON_SAMPLE_GALLERY        4187
#define ID_WRITE_PASTEASHYPERLINK       4188
#define ID_VIEW_ZOOMFIT                 4189
#define ID_ACCELERATOR321ID_SIMULATION_RUN 4190
#define IDS_RIBBON_ALIGN                4191
#define IDS_RIBBON_RIGHTANGLE           4192
#define IDS_RIBBON_RECTANGLE            4193
#define IDS_RIBBON_PARALLELOGRAM        4194
#define IDS_RIBBON_HORIZONTAL           4195
#define IDS_RIBBON_VERTICAL             4196
#define IDS_RIBBON_LINEUP               4197
#define ID_FILE_SAVEVIDEO               4198
#define IDS_RIBBON_SAVEVIDEO            4199
#define IDB_INSERT_POPUP_GALLERY2       4200
#define ID_MECHANISM_RESET              4771
#define ID_MECHANISM_SIMULATE           4772
#define ID_EDIT_COMBINE                 4774
#define ID_EDIT_CONNECT                 4775
#define ID_EDIT_ADDLINK2                4776
#define ID_EDIT_ADDLINK3                4777
#define ID_EDIT_ADDLINK4                4778
#define ID_EDIT_DELETESELECTED          4779
#define ID_EDIT_INSERT                  4789
#define ID_INSERT_CONNECTOR             4790
#define ID_INSERT_ANCHOR                4791
#define ID_INSERT_ROTATINGANCHOR        4792
#define ID_INSERT_LINK                  4794
#define ID_EDIT_PROPERTIES              4795
#define ID_EDIT_JOIN                    4796
#define ID_EDIT_GRIDSNAP                4797
#define ID_VIEW_DIMENSIONS              4798
#define ID_VIEW_GROUNDDIMENSIONS        4799
#define ID_EDIT_SPLIT                   4801
#define ID_ALIGN_RIGHTANGLE             4802
#define ID_ALIGN_RECTANGLE              4803
#define ID_ALIGN_PARALLELOGRAM          4804
#define ID_ALIGN_HORIZONTAL             4805
#define ID_ALIGN_VERTICAL               4806
#define ID_ALIGN_LINEUP                 4807
#define ID_INSERT_TRIPLE                4809
#define ID_INSERT_DOUBLE                4811
#define ID_VIEW_LABELS                  4814
#define ID_VIEW_DATA                    4817
#define ID_VIEW_DEBUG                   4818
#define ID_VIEW_ANTIALIAS               4819
#define ID_EDIT_SNAP                    4820
#define ID_HELP_LOADEXAMPLE1            4821
#define ID_HELP_LOADEXAMPLE2            4822
#define ID_HELP_LOADEXAMPLE3            4823
#define ID_HELP_LOADEXAMPLE4            4824
#define ID_HELP_LOADEXAMPLE5            4825
#define ID_HELP_LOADEXAMPLE6            4826
#define ID_HELP_LOADEXAMPLE7            4827
#define ID_HELP_LOADEXAMPLE8            4828
#define ID_HELP_LOADEXAMPLE9            4829
#define ID_HELP_LOADEXAMPLE10           4830
#define ID_HELP_LOADEXAMPLE11           4831
#define ID_HELP_LOADEXAMPLE12           4832
#define ID_HELP_LOADEXAMPLE13           4833
#define ID_HELP_LOADEXAMPLE14           4834
#define ID_HELP_LOADEXAMPLE15           4835
#define ID_HELP_LOADEXAMPLE16           4836
#define ID_VIEW_ZOOMIN                  4837
#define ID_VIEW_ZOOMOUT                 4838
#define ID_FILE_PP                      4843
#define ID_HELP_USER                    4846
#define ID_HELP_USERGUIDE               4847
#define ID_FILE_SAMPLES                 4848
#define ID_INSERTLINK_ANCHOR            4849
#define ID_BUTTON32850                  4850
#define ID_SELECT_NEXT                  4851
#define ID_VIEW_ANGLES                  4852
#define ID_EDIT_SLIDE                   4863
#define ID_EDIT_SLIDE32865              4865
#define IDB_WRITESMALL                  4867
#define IDB_WRITELARGE                  4868
#define IDB_MAIN                        4869
#define IDB_BUTTONS                     4870
#define IDB_FILELARGE                   4871
#define IDB_FILESMALL                   4872
#define ID_STATUSBAR_PANE1              4874
#define ID_STATUSBAR_PANE2              4875
#define IDS_STATUS_PANE1                4876
#define IDS_STATUS_PANE2                4877
#define IDS_RIBBON_LABELS               4879
#define IDS_RIBBON_ZOOM                 4880
#define IDS_RIBBON_ZOOMFIT              4881
#define IDS_RIBBON_SNAP                 4884
#define ID_INSERT_SLIDER                4885
#define ID_INSERT_LINK2                 4886
#define ID_INSERT_LINK3                 4887
#define ID_INSERT_LINK4                 4888
#define ID_INSERT_INPUT                 4889
#define IDS_RIBBON_INSERT_CONNECTOR     4890
#define IDS_RIBBON_INSERT_SLIDER        4891
#define IDS_RIBBON_INSERT_LINK2         4892
#define IDS_RIBBON_INSERT_LINK3         4893
#define IDS_RIBBON_INSERT_ANCHOR        4894
#define IDS_RIBBON_INSERT_INPUT         4895
#define IDR_PASTE_MENU                  4896
#define IDR_WINDOWS_MENU                4897
#define ID_VIEW_NAVIGATION              4898
#define IDB_NAVIGATION_LARGE            4899
#define ID_HELP_USERGUIDE_TIP           4900
#define ID_HELP_USERGUIDE_DESCRIPTION   4901
#define IDS_RIBBON_PROPERTIES_PROPERTIES 4903
#define ID_PROPERTIES_PROPERTIES        4904
#define IDS_RIBBON_SIMULATEMANUAL       4905
#define ID_SIMULATE_MANUAL              4906
#define IDS_RIBBON_GRIDSNAP             4907
#define ID_HELP_ABOUT_TIP               4908
#define ID_HELP_ABOUT_DESCRIPTION       4909
#define ID_HELP_ABOUT                   4910
#define IDS_RIBBON_ANGLES               4911
#define IDS_RIBBON_VIEW_ANICROP         4912
#define IDS_RIBBON_VIEW_UNITS           4913
#define ID_VIEW_UNITS                   4914
#define IDS_RIBBON_VIEW_BOLD            4915
#define ID_VIEW_BOLD                    4916
#define IDS_RIBBON_DIM                  4917
#define ID_VIEW_COORDINATES             4918
#define IDS_RIBBON_FLIPH                4919
#define IDS_RIBBON_FLIPV                4920
#define ID_ALIGN_FLIPV                  4921
#define ID_ALIGN_FLIPH                  4922
#define IDS_RIBBON_PIN                  4923
#define ID_SIMULATION_PIN               4924
#define IDS_RIBBON_CONFIG               4925
#define IDS_RIBBON_ALIGNBUTTON          4926
#define ID_ALIGN_ALIGNBUTTON            4927
#define IDS_RIBBON_INSERTBUTTON         4928
#define ID_EDIT_INSERTBUTTON            4929
#define IDS_RIBBON_SAMPLE_GALLERY       4930
#define IDS_RIBBON_INSERT_LINK4         4931
#define IDS_RIBBON_PRINTING             4932
#define IDS_RIBBON_PRINTOPTIONS         4933
#define IDS_RIBBON_PRINTFULL            4934
#define IDS_SAMPLE_SIMPLE               5011
#define IDS_SAMPLE_JANSEN               5012
#define IDS_SAMPLE_KLANN                5013
#define IDS_SAMPLE_JOULES               5014
#define IDS_SAMPLE_HOEKEN               5015
#define IDS_SAMPLE_PARALLEL             5016
#define IDS_SAMPLE_FOLDINGTOP           5017
#define IDS_SAMPLE_SLIDING1             5018
#define IDS_SAMPLE_SLIDING2             5019
#define IDS_SAMPLE_LINK1                5020
#define IDS_SAMPLE_LINK2                5021
#define IDS_SAMPLE_SMILE                5022
#define IDS_SAMPLE_LINK3                5026
#define IDS_SAMPLE_LINK4                5027
#define ID_MECHANISM_SIMULATEINTERACTIVE 5028
#define ID_INSERTLINK_ACTUATOR          5029
#define IDS_RIBBON_DIMENSIONS           5030
#define ID_VIEW_ANICROP                 5031
#define ID_EDIT_LOCK                    5032
#define IDS_RIBBON_LOCK                 5033
#define IDS_RIBBON_GROUNDDIMENSIONS     5034
#define ID_SAMPLE_SIMPLE                5100
#define ID_SAMPLE_ACTUATOR              5101
#define ID_SAMPLE_ACTUATOR2             5102
#define ID_SAMPLE_ACTUATOR3             5103
#define ID_SAMPLE_COMPLICATED           5104
#define ID_SAMPLE_JANSEN                5105
#define ID_SAMPLE_KLANN                 5106
#define ID_SAMPLE_JOULES                5107
#define ID_SAMPLE_HOEKEN                5108
#define ID_SAMPLE_PARALLEL              5109
#define ID_SAMPLE_FOLDINGTOP            5110
#define ID_SAMPLE_SLIDING1              5111
#define ID_SAMPLE_SLIDING2              5112
#define ID_SAMPLE_LINK1                 5113
#define ID_SAMPLE_LINK2                 5114
#define ID_SAMPLE_SMILE                 5115
#define ID_SAMPLE_LINK3                 5116
#define ID_SAMPLE_LINK4                 5117
#define ID_SAMPLE_PEAUCELLIER           5118
#define ID_SAMPLE_SCISSORS              5119
#define ID_SAMPLE_VARYSPEED             5120
#define ID_SAMPLE_FINGERBOX             5121
#define ID_SAMPLE_WATT                  5122
#define ID_SAMPLE_THROW                 5123
#define ID_SAMPLE_PISTON                5124
#define ID_SAMPLE_CURVEDSLIDER          5125
#define ID_SAMPLE_CURVEDSLIDER2         5126
#define ID_SAMPLE_CHEBYSHEV             5127
#define ID_SAMPLE_DOUBLECURVESLIDE      5128
#define ID_SAMPLE_LIFTER                5129
#define ID_SAMPLE_FOURGEARS             5130
#define ID_SAMPLE_ORBITGEARS            5131
#define ID_SAMPLE_OSCILLATORGEARS       5132
#define ID_SAMPLE_STEPHENSON            5133
#define ID_SAMPLE_UNUSED17              5134
#define ID_SAMPLE_UNUSED18              5135
#define ID_SAMPLE_UNUSED19              5136
#define ID_SAMPLE_UNUSED20              5137
#define ID_SAMPLE_UNUSED21              5138
#define ID_SAMPLE_UNUSED22              5139
#define ID_SAMPLE_UNUSED23              5140
#define ID_SAMPLE_UNUSED24              5141
#define ID_SAMPLE_UNUSED25              5142
#define ID_POPUP_GALLERY                5198
#define IDB_BITMAP5                     5199
#define IDB_PLAY                        5200
#define IDB_BITMAP3                     5201
#define IDB_BITMAP6                     5204
#define IDI_ICON7                       5205
#define ID_EDIT_AUTOJOIN                5206
#define IDI_ICON9                       5206
#define IDS_RIBBON_AUTOJOIN             5207
#define IDD_DIALOG2                     5207
#define IDD_ANGLE                       5207
#define IDS_RIBBON_EVENSPACE            5208
#define IDB_CONNECTOR                   5208
#define ID_ALIGN_EVENSPACE              5209
#define IDS_MENU_SAMPLE_GALLERY         5210
#define IDB_ANCHOR                      5210
#define ID_FILE_SAVEIMAGE               5211
#define IDS_RIBBON_SAVEIMAGE            5212
#define IDB_INPUT                       5212
#define IDS_RIBBON_SETANGLE             5213
#define ID_ALIGN_SETANGLE               5214
#define ID_VIEW_DRAWING                 5215
#define IDD_GEAR_RATIO_DIALOG           5215
#define IDS_RIBBON_VIEWDRAWING          5216
#define ID_VIEW_MECHANISM               5217
#define IDS_RIBBON_VIEWMECHANISM        5218
#define ID_INSERT_POINT                 5219
#define ID_INSERT_LINE                  5220
#define IDS_RIBBON_INSERT_POINT         5221
#define IDS_RIBBON_INSERT_LINE          5222
#define ID_EDIT_DRAWING                 5223
#define IDS_RIBBON_EDITDRAWING          5224
#define ID_EDIT_MECHANISM               5225
#define IDS_RIBBON_EDITMECHANISM        5226
#define ID_ALIGN_SNAPBUTTON             5227
#define IDS_RIBBON_UNDO                 5228
#define ID_ALIGN_DETAILSBUTTON          5229
#define ID_EDIT_ADDCONNECTOR            5230
#define IDS_RIBBON_ADDCONNECTOR         5231
#define ID_INSERT_MEASUREMENT           5232
#define IDS_RIBBON_INSERTMEASUREMENT    5233
#define IDS_SAMPLE_THROW                5234
#define IDS_SAMPLE_PISTON               5235
#define IDS_RIBBON_FASTEN               5236
#define ID_EDIT_FASTEN                  5237
#define ID_INSERT_ANCHORLINK            5238
#define IDS_SAMPLE_LIFTER               5240
#define IDC_COPYRIGHT                   5303
#define IDC_COMBO1                      5303
#define IDC_COMBO2                      5304
#define IDC_EDIT3                       5305
#define IDS_RIBBON_SOLIDLINKS           5306
#define ID_VIEW_SOLIDLINKS              5307
#define IDC_EDIT5                       5307
#define IDS_SAMPLE_CURVEDSLIDER         5308
#define IDS_SAMPLE_CURVEDSLIDER2        5309
#define IDS_SAMPLE_CHEBYSHEV            5310
#define IDC_CHECK4                      5313
#define IDC_NAMEPROMPT                  5314
#define IDC_THROWDISTANCEPROMPT         5315
#define IDC_RADIUSPROMPT                5316
#define IDC_CHECK5                      5316
#define IDC_SLIDERADIUSMINPROMPT        5317
#define IDC_CHECK6                      5317
#define IDC_LOCKED                      5317
#define IDC_SLIDRADIUSMINVALUE          5318
#define IDC_FILENAME                    5319
#define IDC_TITLE                       5320
#define IDC_VERSION                     5321
#define IDS_RIBBON_INSERT_ANCHORLINK    5322
#define IDS_SAMPLE_DOUBLECURVESLIDE     5323
#define IDS_RIBBON_EXPORT               5324
#define IDS_RIBBON_EXPORTDXF            5325
#define IDS_RIBBON_EXPORT_LABEL         5326
#define ID_FILE_SAVEDXF                 5327
#define IDS_RIBBON_SAVEDXF              5328
#define ID_FILE_SAVEMOTION              5329
#define IDS_RIBBON_SAVEMOTION           5330
#define ID_VIEW_ZMOUT                   5400
#define ID_ACCELERATOR39002             5402
#define ID_ACCELERATOR39004             5404
#define IDS_RIBBON_SETTINGS             5405
#define IDS_RIBBON_SETTINGSOPTIONS      5406
#define IDS_RIBBON_VIEW_LARGEFONT       5407
#define ID_VIEW_LARGEFONT               5408
#define ID_INSERT_GEAR                  5409
#define IDS_RIBBON_INSERTGEAR           5410
#define IDC_NAME1                       5411
#define IDC_NAME2                       5412
#define IDS_RIBBON_UNFASTEN             5413
#define ID_EDIT_UNFASTEN                5414
#define IDC_FASTENEDTO                  5415
#define IDC_COLOR                       5416
#define IDC_COLORPROMPT                 5417
#define IDC_COLOR2                      5417
#define IDC_GEARRADIUSPROMPT            5418
#define IDS_SAMPLE_FOURGEARS            5419
#define IDS_SAMPLE_ORBITGEARS           5420
#define IDS_SAMPLE_OSCILLATORGEARS      5421
#define IDS_SAMPLE_STEPHENSON           5422
#define IDS_SAMPLE_PEAUCELLIER          5423
#define IDS_RIBBON_VIEW_GRID            5424
#define ID_VIEW_GRID                    5425
#define IDS_RIBBON_VIEW_PARTS           5426
#define ID_VIEW_PARTS                   5427
#define ID_FILE_PRINTFULL               5935
#define IDD_EXPORTIMAGE                 6000
#define IDC_PREVIEW                     8000

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        6004
#define _APS_NEXT_COMMAND_VALUE         7002
#define _APS_NEXT_CONTROL_VALUE         8001
#define _APS_NEXT_SYMED_VALUE           9000
#endif
#endif
